// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Greeting$Whatever = require("./Greeting.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Greeting$Whatever.make("TESTE", /* array */[])), "app");

/*  Not a pure module */
